# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.define "web" do |web|
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end
  end
end
